# Generated by Django 4.2.16 on 2024-11-23 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0002_alter_match_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='n_players',
            field=models.IntegerField(default=0),
        ),
    ]
